// ============================================================
// DAX Query: Zagrożone zamówienia (marża < 5%)
// Użycie: Power Automate → Power BI connector → "Run a query"
// ============================================================

// ----- TABELA 1: Zagrożone zamówienia per Key_Sales_CuS -----
EVALUATE
VAR _MarginThreshold = 0.05
RETURN
FILTER(
    SELECTCOLUMNS(
        '04_Open_Orders',
        "Key_Sales_CuS",       '04_Open_Orders'[Key_Sales_CuS],
        "Sales_Order",         '04_Open_Orders'[Sales order],
        "Line_No",             '04_Open_Orders'[Line No],
        "Item_Number",         '04_Open_Orders'[Item number],
        "Name",                '04_Open_Orders'[Name],
        "Customer_Account",    '04_Open_Orders'[Customer account],
        "Quantity",            '04_Open_Orders'[Quantity],
        "Unit_Price",          '04_Open_Orders'[Unit price],
        "Net_Amount",          '04_Open_Orders'[Net amount],
        "Amount_EUR",          '04_Open_Orders'[Amount in EUR],
        "COGS_EUR",            '04_Open_Orders'[COGS in EUR],
        "Margin",              '04_Open_Orders'[Margin],
        "Vendor",              '04_Open_Orders'[Vendor],
        "Confirmed_Ship_Date", '04_Open_Orders'[Confirmed ship date],
        "Requested_Ship_Date", '04_Open_Orders'[Requested ship date]
    ),
    [Margin] < _MarginThreshold
)
ORDER BY [Key_Sales_CuS], [Margin] ASC


// ----- TABELA 2: Ceny sprzedaży wg cennika dla zagrożonych produktów -----
// Logika: aktualna cena (TODAY() między From/To) lub ostatnia historyczna
EVALUATE
VAR _Today = TODAY()
VAR _ThreatenedItems =
    CALCULATETABLE(
        DISTINCT('04_Open_Orders'[Item number]),
        '04_Open_Orders'[Margin] < 0.05
    )
// Wszystkie ceny sprzedaży dla zagrożonych produktów
VAR _AllSalesPrices =
    FILTER(
        SELECTCOLUMNS(
            'BOMCalc06_item_prices_AX_sales',
            "Item_Number",      'BOMCalc06_item_prices_AX_sales'[Item number],
            "Price_EUR",        'BOMCalc06_item_prices_AX_sales'[Price],
            "Currency",         'BOMCalc06_item_prices_AX_sales'[Currency],
            "Unit",             'BOMCalc06_item_prices_AX_sales'[Unit],
            "From_Date",        'BOMCalc06_item_prices_AX_sales'[From date],
            "To_Date",          'BOMCalc06_item_prices_AX_sales'[To date],
            "Customer_Account", 'BOMCalc06_item_prices_AX_sales'[Customer account]
        ),
        [Item_Number] IN _ThreatenedItems
    )
// Ceny aktualnie obowiązujące
VAR _CurrentPrices =
    FILTER(
        _AllSalesPrices,
        [From_Date] <= _Today && ([To_Date] >= _Today || ISBLANK([To_Date]))
    )
// Produkty, które mają aktualną cenę
VAR _ItemsWithCurrentPrice =
    SELECTCOLUMNS(_CurrentPrices, "Item", [Item_Number])
// Dla produktów BEZ aktualnej ceny — ostatnia historyczna (max From_Date)
VAR _MaxHistoricalDates =
    FILTER(
        ADDCOLUMNS(
            _ThreatenedItems,
            "MaxFromDate",
                CALCULATE(
                    MAX('BOMCalc06_item_prices_AX_sales'[From date]),
                    'BOMCalc06_item_prices_AX_sales'[From date] < _Today
                )
        ),
        NOT([Item number] IN _ItemsWithCurrentPrice)
    )
VAR _HistoricalPrices =
    FILTER(
        _AllSalesPrices,
        NOT([Item_Number] IN _ItemsWithCurrentPrice)
            && [From_Date] = MAXX(
                FILTER(_MaxHistoricalDates, [Item number] = EARLIER([Item_Number])),
                [MaxFromDate]
            )
    )
// Wynik: aktualne + ostatnie historyczne
RETURN
UNION(_CurrentPrices, _HistoricalPrices)
ORDER BY [Item_Number]


// ----- TABELA 3: Ceny zakupu dla zagrożonych produktów -----
// Logika: aktualna cena (TODAY() >= From_Date) lub ostatnia historyczna
EVALUATE
VAR _Today = TODAY()
VAR _ThreatenedItems =
    CALCULATETABLE(
        DISTINCT('04_Open_Orders'[Item number]),
        '04_Open_Orders'[Margin] < 0.05
    )
// Wszystkie ceny zakupu dla zagrożonych produktów
VAR _AllPurchasePrices =
    FILTER(
        SELECTCOLUMNS(
            'BOMCalc06_item_prices_AX_purchase',
            "Item_Number",      'BOMCalc06_item_prices_AX_purchase'[Item number],
            "Price_EUR",        'BOMCalc06_item_prices_AX_purchase'[Price],
            "Currency",         'BOMCalc06_item_prices_AX_purchase'[Currency],
            "Unit",             'BOMCalc06_item_prices_AX_purchase'[Unit],
            "From_Date",        'BOMCalc06_item_prices_AX_purchase'[From date],
            "Vendor",           'BOMCalc06_item_prices_AX_purchase'[Vendor account],
            "Vendor_Name",      'BOMCalc06_item_prices_AX_purchase'[Vendor name]
        ),
        [Item_Number] IN _ThreatenedItems
    )
// Ceny aktualnie obowiązujące (From_Date <= dziś, brak To_Date w cenach zakupu)
VAR _CurrentPrices =
    FILTER(
        _AllPurchasePrices,
        [From_Date] <= _Today
    )
// Najnowsza cena per Item + Vendor (max From_Date)
VAR _LatestPerItemVendor =
    GROUPBY(
        _CurrentPrices,
        [Item_Number],
        [Vendor],
        "MaxFromDate", MAXX(CURRENTGROUP(), [From_Date])
    )
// Filtruj tylko wiersze z najnowszą datą per Item + Vendor
VAR _BestPurchasePrices =
    FILTER(
        _CurrentPrices,
        VAR _thisItem = [Item_Number]
        VAR _thisVendor = [Vendor]
        VAR _maxDate =
            MAXX(
                FILTER(_LatestPerItemVendor, [Item_Number] = _thisItem && [Vendor] = _thisVendor),
                [MaxFromDate]
            )
        RETURN [From_Date] = _maxDate
    )
// Jeśli produkt nie ma żadnej ceny z From <= dziś, weź ostatnią dostępną
VAR _ItemsWithPrice =
    SELECTCOLUMNS(_BestPurchasePrices, "Item", [Item_Number])
VAR _FallbackPrices =
    FILTER(
        _AllPurchasePrices,
        NOT([Item_Number] IN _ItemsWithPrice)
            && [From_Date] = MAXX(
                FILTER(_AllPurchasePrices, [Item_Number] = EARLIER([Item_Number])),
                [From_Date]
            )
    )
RETURN
UNION(_BestPurchasePrices, _FallbackPrices)
ORDER BY [Item_Number]
